import React, { ReactNode } from 'react';
import Head from 'next/head';

export default function Layout({ children }: { children: ReactNode }) {
	return (
		<>
			<Head>
				<title>Villa Life</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='bg-[url(https://images.unsplash.com/photo-1618064541372-289bdb6f5b7b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=3600&q=80)] bg-black bg-opacity-30 bg-center bg-blend-overlay'>
				{children}
			</main>
		</>
	);
}
