import React, { ReactNode } from 'react';
import Head from 'next/head';
import Image from 'next/image';

export default function Layout({ children }: { children: ReactNode }) {
	return (
		<>
			<Head>
				<title>Villa Life</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='bg-black'>
				<div className='absolute left-0 top-0'>
					<Image
						alt='logo'
						src='/logo.png'
						width={300}
						height={100}
					/>
				</div>
				{children}
			</main>
		</>
	);
}
